const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const nodes=new Map(),element=()=>({innerHTML:'',textContent:'',style:{},value:'',open:false,close(){this.open=false},showModal(){this.open=true}});
const sandbox={console,Date,Intl,setInterval(){},clearTimeout(){},setTimeout(){},navigator:{onLine:true},window:{addEventListener(){}},localStorage:{getItem(){return null},setItem(){}},document:{querySelector(s){if(!nodes.has(s))nodes.set(s,element());return nodes.get(s)},querySelectorAll(){return[]}}};
vm.createContext(sandbox);vm.runInContext(fs.readFileSync('dist/app.js','utf8'),sandbox);const run=code=>vm.runInContext(code,sandbox);
assert.equal(run('enough({marg:1})'),true);assert.equal(run('enough({marg:500})'),false);
run('state.stock.burrata.qty=1; state.hold={items:{burrata:1},slot:state.slots[0],expires:Date.now()+300000}');assert.equal(run('enough({burrata:1})'),false);assert.equal(run('enough({burrata:1},false)'),true);
run('state.hold.expires=Date.now()-1; expire()');assert.equal(run('state.hold'),null);assert.equal(run('enough({burrata:1})'),true);
run('state=initial(); state.capacity=load(state.slots[0]); cart={marg:1}; selected=0; actions.checkout()');assert.equal(run('state.hold'),null);assert.equal(run('selected'),1);
run('actions.checkout()');assert.equal(run('qty(state.hold.items)'),1);const stockBefore=run('state.stock.dough.qty');run('payment(); document.querySelector("#customer").value="Test"; document.querySelector("#pay").onclick()');assert.equal(run('state.stock.dough.qty'),stockBefore-1);assert.equal(run('state.orders.at(-1).status'),'QUEUED');assert.equal(run('state.hold'),null);
run('advance(1048); advance(1048); advance(1048)');assert.equal(run('state.orders.at(-1).status'),'READY');assert.equal(run('state.notifications.length'),1);run('advance(1048);advance(1048)');assert.equal(run('state.orders.at(-1).status'),'COLLECTED');
run('state.pausedUntil=Date.now()+60000;cart={marg:1};actions.checkout()');assert.equal(run('state.hold'),null);
run('state.stock.mozza.qty=0');assert.equal(run('enough({marg:1})'),false);
console.log('PASS: BOM, stock holds, TTL rollback, quota fallback, simulated payment, manual lifecycle, pause and ingredient rupture.');
